name: Deploy
run-name: ${{ github.actor }} is deploying 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      uses: easingthemes/ssh-deploy@main
      with:
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{secrets.REMOTE_PORT}}
        TARGET: ${{ secrets.REMOTE_TARGET }}